version: '3.8'

x-common-variables:
  &common-variables
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_ROOT_PASSWORD

services:

  mysql_db:
    container_name: app_mysql
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./db/db.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost
      
  nginx:
    container_name: app_nginx
    depends_on:
      - api
      - app_react
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    container_name: app_api
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  app_react:
    container_name: app_react
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  adminer:
    container_name: app_adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
